apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  selector:
      matchLabels:
        app: kubernetes-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - name: kubernetes-demo
          image: kubernetes-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: "/deployments/config"
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: kubernetes-demo
          items:
          - key: kubernetes-prop.yml
            path: kubernetes-prop.yml